pipeline {
    agent any

    stages {
        stage('Init') {
            steps {
                git url: 'git@github.com:mkutsybala/EPAM-Project-v3.git', branch: 'dev', credentialsId: 'Jenkins_KEY'
            }
        }
        stage('Build image') {
            steps {
                git url: 'git@github.com:mkutsybala/EPAM-Project-v3.git', branch: 'docker', credentialsId: 'Jenkins_KEY'
                docker build -t mkutsybala/epam_project:latest ./docker/
                docker push mkutsybala/epam_project:latest
            }
        }
        stage('Build inftastructure') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
        stage('Destroy infrastructure') {
            steps {
                echo 'Destroying....'
            }
        }
    }
}