pipeline {
    agent any

    stages {
        stage('Build image') {
            steps {
                echo 'Building..'
            }
        }
        stage('Build inftastructure') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
        stage('Destroy infrastructure') {
            steps {
                echo 'Destroying....'
            }
        }
    }
}