pipeline {
    agent any

    stages {
        stage('Build image') {
            steps {
                git url: 'git@github.com:mkutsybala/EPAM-Project-v3.git', credentialsId: 'Jenkins_KEY'
                //docker build -t mkutsybala/epam_project:latest ./dev/
                //docker push mkutsybala/epam_project:latest
            }
        }
        stage('Build inftastructure') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
        stage('Destroy infrastructure') {
            steps {
                echo 'Destroying....'
            }
        }
    }
}