---
# tasks file for pull_and_run_container_with_webapp
- name: Run webapp container
  docker_container:
    name: webapp
    state: started
    recreate: yes
    image: "mkutsybala/epam_project:{{ lookup('env','BUILD_NUMBER') }}"
    pull: yes
    exposed_ports:
     - "80"
    published_ports:
     - "0.0.0.0:80:80"